version: '3'
services:
  api:
    image: openrecord/turntable
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 7001:7001
    volumes:
      - ./src:/app/src
    depends_on:
      - mysql
    command: node_modules/.bin/nodemon

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/mount:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306