[build]
  functions = "./built/functions"
  command = "npm run deploy"
  env = { ENDPOINT="https://us1.prisma.sh/jamesscottmcnamara/turntable/staging" }

[context.production]
  env = { ENDPOINT="https://us1.prisma.sh/jamesscottmcnamara/turntable/dev" }

[context.develop]
  env = { ENDPOINT="https://us1.prisma.sh/jamesscottmcnamara/turntable/staging" }