[build]
  functions = "./built/functions"
  command = "npm run deploy"
  environment = { ENDPOINT = "http://localhost:4466/" }

[context.production]
  environment = { ENDPOINT = "https://us1.prisma.sh/jamesscottmcnamara/turntable/dev" }

[context.develop]
  environment = { ENDPOINT = "https://us1.prisma.sh/jamesscottmcnamara/turntable/staging" }