# docs.serverless.com

service: openrecord-turntable

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions:
  proxy:
    handler: src/app/functions.proxy
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-offline